// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDugf4hvf4LyBkjuoU1HaSzWmo-wtWhPts',
    appId: '1:300793109936:web:0b82cb7bcc9961c63fca75',
    messagingSenderId: '300793109936',
    projectId: 'coupchat1',
    authDomain: 'coupchat1.firebaseapp.com',
    storageBucket: 'coupchat1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4BFmo2t7rYVTfkiE7EFbF0DRsWr5grvU',
    appId: '1:300793109936:android:a7931a9a9db45bac3fca75',
    messagingSenderId: '300793109936',
    projectId: 'coupchat1',
    storageBucket: 'coupchat1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArtlSi6ILRGfnCYQOrYZaIf4FoG9jhm1c',
    appId: '1:300793109936:ios:a94de58fd353126b3fca75',
    messagingSenderId: '300793109936',
    projectId: 'coupchat1',
    storageBucket: 'coupchat1.appspot.com',
    iosBundleId: 'com.example.coupchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArtlSi6ILRGfnCYQOrYZaIf4FoG9jhm1c',
    appId: '1:300793109936:ios:a94de58fd353126b3fca75',
    messagingSenderId: '300793109936',
    projectId: 'coupchat1',
    storageBucket: 'coupchat1.appspot.com',
    iosBundleId: 'com.example.coupchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDugf4hvf4LyBkjuoU1HaSzWmo-wtWhPts',
    appId: '1:300793109936:web:369f1bb75b931d493fca75',
    messagingSenderId: '300793109936',
    projectId: 'coupchat1',
    authDomain: 'coupchat1.firebaseapp.com',
    storageBucket: 'coupchat1.appspot.com',
  );
}
